spring:
   cloud:
    config:
      server:
        git:
          uri: https://github.com/shengtu0328/spring-cloud-demo.git
          search-paths: config-repo
      label: master
   application:
     name: config-server


server:
  port: 8888